import {
  PlacedBuilding,
  Flight,
  AircraftEntity,
  PassengerEntity,
  VehicleEntity,
  StaffDepartment,
  AirlineContract,
  WeatherState,
  AirportGameEvent,
  AirportFinances,
  ResearchTech,
  CityFacility,
  WorldHub,
  GameMode,
} from '../types';

export interface AirportSimState {
  gameMode: GameMode;
  level: number;
  levelTitle: string;
  xp: number;
  xpToNextLevel: number;
  reputation: number; // 0-100
  timeString: string; // "14:32"
  gameDay: number;
  dayOfWeek: string;
  simSpeed: number; // 0 = pause, 1 = 1x, 2 = 2x, 4 = 4x
  totalPassengersProcessed: number;
  activePassengersCount: number;

  buildings: PlacedBuilding[];
  flights: Flight[];
  aircraft: AircraftEntity[];
  passengers: PassengerEntity[];
  vehicles: VehicleEntity[];
  staff: StaffDepartment[];
  contracts: AirlineContract[];
  weather: WeatherState;
  events: AirportGameEvent[];
  finances: AirportFinances;
  research: ResearchTech[];
  cityFacilities: CityFacility[];
  worldHubs: WorldHub[];

  selectedFlightId: string | null;
  selectedEntityId: string | null; // aircraft or passenger or building
  selectedBuildingDefId: string | null; // For build mode preview
  buildModeActive: boolean;

  // Camera state
  camera: {
    x: number;
    y: number;
    zoom: number; // 0.35 to 2.5
    followingEntityId: string | null;
    targetZoom: number;
  };
}

export const INITIAL_STAFF: StaffDepartment[] = [
  {
    id: 'staff_checkin',
    name: 'Check-in Counter Agents',
    count: 14,
    salaryPerHead: 140,
    efficiency: 92,
    icon: 'Users',
    description: 'Verifies tickets, checks baggage, and issues boarding passes quickly.',
  },
  {
    id: 'staff_security',
    name: 'TSA Security Officers',
    count: 12,
    salaryPerHead: 175,
    efficiency: 88,
    icon: 'ShieldCheck',
    description: 'Manages carry-on X-ray scanners, body scanners, and metal detectors.',
  },
  {
    id: 'staff_ground',
    name: 'Ramp Agents & Pushback Crew',
    count: 16,
    salaryPerHead: 155,
    efficiency: 90,
    icon: 'Truck',
    description: 'Performs aircraft marshalling, baggage cart towing, and pushback operations.',
  },
  {
    id: 'staff_atc',
    name: 'Air Traffic Controllers',
    count: 6,
    salaryPerHead: 320,
    efficiency: 96,
    icon: 'Radio',
    description: 'Controls runway approach, sequencing, takeoff clearance, and ground taxi paths.',
  },
  {
    id: 'staff_maintenance',
    name: 'Licensed Aircraft Technicians',
    count: 8,
    salaryPerHead: 240,
    efficiency: 85,
    icon: 'Wrench',
    description: 'Conducts pre-flight mechanical checks, tire inspections, and repairs.',
  },
  {
    id: 'staff_cleaners',
    name: 'Cabin Cleaning & Janitorial',
    count: 18,
    salaryPerHead: 110,
    efficiency: 94,
    icon: 'Sparkles',
    description: 'Keeps terminal concourses pristine and turns around aircraft cabins rapidly.',
  },
];

export const INITIAL_CONTRACTS: AirlineContract[] = [
  {
    id: 'contract_skyways',
    airline: 'SkyWays',
    flightsPerDay: 8,
    payoutPerDay: 48000,
    requiredReputation: 60,
    requiredGates: 1,
    active: true,
    minOnTimeRate: 80,
  },
  {
    id: 'contract_sunrise',
    airline: 'Sunrise Air',
    flightsPerDay: 6,
    payoutPerDay: 36000,
    requiredReputation: 65,
    requiredGates: 1,
    active: true,
    minOnTimeRate: 82,
  },
  {
    id: 'contract_bluejet',
    airline: 'BlueJet',
    flightsPerDay: 6,
    payoutPerDay: 42000,
    requiredReputation: 70,
    requiredGates: 1,
    active: true,
    minOnTimeRate: 85,
  },
  {
    id: 'contract_universal',
    airline: 'Universal Air',
    flightsPerDay: 4,
    payoutPerDay: 54000,
    requiredReputation: 78,
    requiredGates: 1,
    active: true,
    minOnTimeRate: 88,
  },
  {
    id: 'contract_cargolink',
    airline: 'CargoLink',
    flightsPerDay: 4,
    payoutPerDay: 38000,
    requiredReputation: 72,
    requiredGates: 1,
    active: true,
    minOnTimeRate: 80,
  },
  {
    id: 'contract_oceanic',
    airline: 'Oceanic Global Airways',
    flightsPerDay: 5,
    payoutPerDay: 95000,
    requiredReputation: 85,
    requiredGates: 2,
    active: false,
    minOnTimeRate: 90,
  },
];

export const INITIAL_FLIGHTS: Flight[] = [
  {
    id: 'fl_ai102',
    flightNumber: 'AI102',
    airline: 'SkyWays',
    airlineCode: 'SW',
    color: '#0284c7',
    aircraftType: 'A320',
    origin: 'Kochi',
    destination: 'Mumbai',
    gate: 'A1',
    passengers: 134,
    maxPassengers: 150,
    cargoKg: 2400,
    scheduledArrival: '13:45',
    scheduledDeparture: '15:20',
    status: 'Boarding',
    currentStep: 'BOARDING',
    fareRevenue: 28500,
    airlineFee: 6200,
    isCargo: false,
  },
  {
    id: 'fl_sg204',
    flightNumber: 'SG204',
    airline: 'Sunrise Air',
    airlineCode: 'SA',
    color: '#ea580c',
    aircraftType: 'B737',
    origin: 'Bangalore',
    destination: 'Delhi',
    gate: 'A2',
    passengers: 142,
    maxPassengers: 160,
    cargoKg: 2800,
    scheduledArrival: '14:10',
    scheduledDeparture: '15:45',
    status: 'On time',
    currentStep: 'REFUELING',
    fareRevenue: 31200,
    airlineFee: 6500,
    isCargo: false,
  },
  {
    id: 'fl_6e318',
    flightNumber: '6E318',
    airline: 'BlueJet',
    airlineCode: 'BJ',
    color: '#2563eb',
    aircraftType: 'A320',
    origin: 'Chennai',
    destination: 'Hyderabad',
    gate: 'A3',
    passengers: 128,
    maxPassengers: 150,
    cargoKg: 2100,
    scheduledArrival: '14:25',
    scheduledDeparture: '16:00',
    status: 'Arriving',
    currentStep: 'LANDING',
    fareRevenue: 26800,
    airlineFee: 6100,
    isCargo: false,
  },
  {
    id: 'fl_uk721',
    flightNumber: 'UK721',
    airline: 'Universal Air',
    airlineCode: 'UA',
    color: '#7c3aed',
    aircraftType: 'B787',
    origin: 'Mumbai',
    destination: 'Dubai',
    gate: 'A4',
    passengers: 248,
    maxPassengers: 280,
    cargoKg: 8500,
    scheduledArrival: '14:00',
    scheduledDeparture: '16:30',
    status: 'On time',
    currentStep: 'CATERING',
    fareRevenue: 64500,
    airlineFee: 14200,
    isCargo: false,
  },
  {
    id: 'fl_fx556',
    flightNumber: 'FX556',
    airline: 'CargoLink',
    airlineCode: 'CL',
    color: '#059669',
    aircraftType: 'B777F',
    origin: 'Cochin',
    destination: 'Singapore',
    gate: 'C1',
    passengers: 0,
    maxPassengers: 0,
    cargoKg: 34000,
    scheduledArrival: '13:15',
    scheduledDeparture: '15:10',
    status: 'Loading',
    currentStep: 'AT_GATE',
    fareRevenue: 52000,
    airlineFee: 11000,
    isCargo: true,
  },
  {
    id: 'fl_oa901',
    flightNumber: 'OA901',
    airline: 'SkyWays',
    airlineCode: 'SW',
    color: '#0284c7',
    aircraftType: 'A320',
    origin: 'Goa',
    destination: 'Kolkata',
    gate: 'A1',
    passengers: 138,
    maxPassengers: 150,
    cargoKg: 2300,
    scheduledArrival: '16:15',
    scheduledDeparture: '17:35',
    status: 'On time',
    currentStep: 'APPROACHING',
    fareRevenue: 29400,
    airlineFee: 6300,
    isCargo: false,
  },
];

export const INITIAL_EVENTS: AirportGameEvent[] = [
  {
    id: 'ev_1',
    title: 'Flight AI102 is boarding',
    description: 'Passengers are currently passing aerobridge Gate A1.',
    time: '14:20',
    type: 'info',
  },
  {
    id: 'ev_2',
    title: 'Passenger queue at Security',
    description: 'Peak influx at Terminal 1. TSA lanes running at 92% capacity.',
    time: '14:15',
    type: 'warning',
  },
  {
    id: 'ev_3',
    title: 'New airline contract available',
    description: 'SkyHigh Airlines requested 4 daily slots.',
    time: '14:10',
    type: 'contract',
  },
  {
    id: 'ev_4',
    title: 'Revenue earned: $12,450',
    description: 'Concession revenue from Terminal Duty-Free & Skyview Cafes.',
    time: '14:05',
    type: 'finance',
  },
  {
    id: 'ev_5',
    title: 'Weather update: Clear skies',
    description: 'Wind 12 km/h SE, runway visibility optimal at 10+ km.',
    time: '13:50',
    type: 'weather',
  },
];

export const INITIAL_WEATHER: WeatherState = {
  current: 'sunny',
  temperatureC: 24,
  windSpeedKmh: 12,
  windDirection: 'SE',
  visibilityKm: 10,
  forecast: [
    { day: 'Wed', weather: 'rain', tempMin: 18, tempMax: 26 },
    { day: 'Thu', weather: 'sunny', tempMin: 19, tempMax: 28 },
    { day: 'Fri', weather: 'cloudy', tempMin: 20, tempMax: 27 },
  ],
};

export const INITIAL_BUILDINGS: PlacedBuilding[] = [
  // RUNWAY
  {
    id: 'b_runway_1',
    defId: 'runway_standard',
    name: 'Runway 27 / 09',
    category: 'runways',
    x: 4,
    y: 2,
    width: 32,
    height: 4,
    level: 1,
  },
  // TAXIWAY MAIN
  {
    id: 'b_taxiway_1',
    defId: 'taxiway_straight',
    name: 'Parallel Taxiway Bravo',
    category: 'taxiways',
    x: 4,
    y: 7,
    width: 32,
    height: 2,
    level: 1,
  },
  // GATES A1 - A4
  {
    id: 'b_gate_a1',
    defId: 'gate_standard_jetway',
    name: 'Gate A1',
    category: 'gates',
    gateCode: 'A1',
    x: 8,
    y: 11,
    width: 5,
    height: 5,
    level: 2,
    activeFlightId: 'fl_ai102',
  },
  {
    id: 'b_gate_a2',
    defId: 'gate_standard_jetway',
    name: 'Gate A2',
    category: 'gates',
    gateCode: 'A2',
    x: 14,
    y: 11,
    width: 5,
    height: 5,
    level: 2,
    activeFlightId: 'fl_sg204',
  },
  {
    id: 'b_gate_a3',
    defId: 'gate_standard_jetway',
    name: 'Gate A3',
    category: 'gates',
    gateCode: 'A3',
    x: 20,
    y: 11,
    width: 5,
    height: 5,
    level: 2,
    activeFlightId: null,
  },
  {
    id: 'b_gate_a4',
    defId: 'gate_widebody',
    name: 'Gate A4',
    category: 'gates',
    gateCode: 'A4',
    x: 26,
    y: 11,
    width: 6,
    height: 5,
    level: 3,
    activeFlightId: 'fl_uk721',
  },
  // MAIN TERMINAL BUILDING
  {
    id: 'b_terminal_main',
    defId: 'terminal_standard',
    name: 'Terminal 1 Concourse',
    category: 'terminals',
    x: 8,
    y: 17,
    width: 24,
    height: 6,
    level: 2,
  },
  // FUEL STATION (LEFT OF GATES)
  {
    id: 'b_fuel_1',
    defId: 'service_fuel',
    name: 'Main Fuel Depot',
    category: 'services',
    x: 3,
    y: 10,
    width: 4,
    height: 4,
    level: 1,
  },
  // MAINTENANCE HANGAR (RIGHT OF GATES)
  {
    id: 'b_maint_1',
    defId: 'service_maintenance',
    name: 'Hangar Bay 1',
    category: 'services',
    x: 33,
    y: 8,
    width: 5,
    height: 5,
    level: 2,
  },
  // ATC TOWER
  {
    id: 'b_atc_1',
    defId: 'service_atc_tower',
    name: 'ATC Control Tower',
    category: 'services',
    x: 31,
    y: 14,
    width: 3,
    height: 4,
    level: 2,
  },
  // PARKING LOT (BOTTOM LEFT)
  {
    id: 'b_park_1',
    defId: 'trans_parking',
    name: 'Terminal Parking Area',
    category: 'transport',
    x: 3,
    y: 24,
    width: 5,
    height: 7,
    level: 1,
  },
  // AIRPORT HOTEL (BOTTOM CENTER-LEFT)
  {
    id: 'b_hotel_1',
    defId: 'city_hotel',
    name: 'Transit Hotel Express',
    category: 'city',
    x: 9,
    y: 25,
    width: 5,
    height: 4,
    level: 1,
  },
  // CARGO TERMINAL (BOTTOM RIGHT)
  {
    id: 'b_cargo_1',
    defId: 'city_cargo',
    name: 'Cargo Terminal Logistics',
    category: 'city',
    x: 27,
    y: 24,
    width: 6,
    height: 4,
    level: 1,
  },
];

export function createInitialSimState(): AirportSimState {
  return {
    gameMode: 'career',
    level: 4,
    levelTitle: 'Regional Airport Hub',
    xp: 620,
    xpToNextLevel: 1000,
    reputation: 82,
    timeString: '14:32',
    gameDay: 14,
    dayOfWeek: 'Tue, 15 Apr 2025',
    simSpeed: 1,
    totalPassengersProcessed: 4280,
    activePassengersCount: 342,

    buildings: INITIAL_BUILDINGS,
    flights: INITIAL_FLIGHTS,
    aircraft: [],
    passengers: [],
    vehicles: [],
    staff: INITIAL_STAFF,
    contracts: INITIAL_CONTRACTS,
    weather: INITIAL_WEATHER,
    events: INITIAL_EVENTS,
    finances: {
      cash: 1250430,
      dailyIncome: 82450,
      dailyExpenses: 39120,
      netProfit: 43330,
      breakdown: {
        passengerFees: 38200,
        airlineFees: 24800,
        commercialShops: 12450,
        parkingTransport: 4200,
        hotelCity: 2800,
        staffSalaries: 22400,
        maintenance: 11200,
        fuelElectricity: 5520,
      },
      dailyHistory: [
        { day: 10, income: 72000, expenses: 36000, net: 36000 },
        { day: 11, income: 75500, expenses: 37200, net: 38300 },
        { day: 12, income: 78100, expenses: 38000, net: 40100 },
        { day: 13, income: 80400, expenses: 38500, net: 41900 },
        { day: 14, income: 82450, expenses: 39120, net: 43330 },
      ],
    },
    research: [
      {
        id: 'res_kiosks',
        title: 'Self Check-in Touch Kiosks',
        category: 'automation',
        cost: 45000,
        researchTimeSeconds: 60,
        unlocked: true,
        researching: false,
        progress: 100,
        icon: 'Smartphone',
        effect: 'Reduces check-in queue times by -35%',
      },
      {
        id: 'res_egates',
        title: 'Biometric Security e-Gates',
        category: 'passengers',
        cost: 85000,
        researchTimeSeconds: 120,
        unlocked: true,
        researching: false,
        progress: 100,
        icon: 'ScanLine',
        effect: 'Doubles TSA security throughput',
      },
      {
        id: 'res_baggage_auto',
        title: 'High-Speed Belt Conveyors',
        category: 'operations',
        cost: 110000,
        researchTimeSeconds: 180,
        unlocked: false,
        researching: false,
        progress: 40,
        icon: 'Luggage',
        effect: 'Zero baggage mishandling and +20% faster turnaround',
      },
      {
        id: 'res_ils_cat3',
        title: 'ILS Category III All-Weather Avionics',
        category: 'operations',
        cost: 160000,
        researchTimeSeconds: 240,
        unlocked: false,
        researching: false,
        progress: 0,
        icon: 'Radar',
        effect: 'Enables zero-visibility landing during fog & storms',
      },
      {
        id: 'res_metro_line',
        title: 'Downtown High-Speed Metro Link',
        category: 'passengers',
        cost: 250000,
        researchTimeSeconds: 300,
        unlocked: false,
        researching: false,
        progress: 0,
        icon: 'Train',
        effect: '+45% passenger demand and transit concessions',
      },
      {
        id: 'res_heavy_freight',
        title: 'Automated Cargo Pallet Lift Systems',
        category: 'cargo',
        cost: 190000,
        researchTimeSeconds: 220,
        unlocked: false,
        researching: false,
        progress: 0,
        icon: 'Box',
        effect: 'Cargo contract payouts increased by +50%',
      },
    ],
    cityFacilities: [
      {
        id: 'fac_hotel',
        name: 'Airport Grand Hotel & Convention Center',
        cost: 240000,
        dailyIncome: 14500,
        passengerBoost: 15,
        built: true,
        icon: 'Hotel',
        description: 'Luxury layover suites and corporate meeting halls.',
      },
      {
        id: 'fac_dutyfree_mall',
        name: 'Airside Duty-Free Mega Galleria',
        cost: 180000,
        dailyIncome: 22000,
        passengerBoost: 20,
        built: true,
        icon: 'ShoppingBag',
        description: 'Tax-free perfumes, high-end timepieces, and gourmet chocolates.',
      },
      {
        id: 'fac_metro_depot',
        name: 'Express Airport Metro Terminal',
        cost: 320000,
        dailyIncome: 18500,
        passengerBoost: 35,
        built: false,
        icon: 'Train',
        description: 'Direct 12-minute transit connection directly to city downtown.',
      },
      {
        id: 'fac_solar_farm',
        name: 'Clean Solar Energy Apron Array',
        cost: 150000,
        dailyIncome: 8500,
        passengerBoost: 0,
        built: false,
        icon: 'Sun',
        description: 'Reduces airport electricity expenses by 45%.',
      },
    ],
    worldHubs: [
      {
        id: 'hub_kochi',
        name: 'Cochin Regional Airport (COK)',
        city: 'Kochi',
        country: 'India',
        demandFactor: 1.0,
        unlocked: true,
        requiredAirportLevel: 1,
        unlockCost: 0,
        icon: 'Palmtree',
      },
      {
        id: 'hub_mumbai',
        name: 'Chhatrapati International Hub (BOM)',
        city: 'Mumbai',
        country: 'India',
        demandFactor: 1.8,
        unlocked: true,
        requiredAirportLevel: 3,
        unlockCost: 250000,
        icon: 'Building2',
      },
      {
        id: 'hub_dubai',
        name: 'Emirates Mega Hub (DXB)',
        city: 'Dubai',
        country: 'UAE',
        demandFactor: 2.6,
        unlocked: false,
        requiredAirportLevel: 4,
        unlockCost: 650000,
        icon: 'Sparkles',
      },
      {
        id: 'hub_singapore',
        name: 'Changi Global Gateway (SIN)',
        city: 'Singapore',
        country: 'Singapore',
        demandFactor: 3.2,
        unlocked: false,
        requiredAirportLevel: 5,
        unlockCost: 1200000,
        icon: 'Plane',
      },
      {
        id: 'hub_london',
        name: 'Heathrow International (LHR)',
        city: 'London',
        country: 'United Kingdom',
        demandFactor: 3.8,
        unlocked: false,
        requiredAirportLevel: 5,
        unlockCost: 2000000,
        icon: 'Landmark',
      },
    ],

    selectedFlightId: 'fl_ai102',
    selectedEntityId: 'fl_ai102',
    selectedBuildingDefId: null,
    buildModeActive: false,

    camera: {
      x: 1000,
      y: 750,
      zoom: 0.65, // Airport View standard
      followingEntityId: null,
      targetZoom: 0.65,
    },
  };
}
