import { BuildingDef } from '../types';

export const BUILDING_CATALOG: BuildingDef[] = [
  // RUNWAYS
  {
    id: 'runway_regional',
    name: 'Regional Runway (1800m)',
    category: 'runways',
    cost: 150000,
    maintenanceCost: 450,
    width: 24,
    height: 3,
    description: 'Capable of handling turboprops and regional jets up to 80 passengers.',
    color: '#334155',
    icon: 'Plane',
    requiredLevel: 1,
  },
  {
    id: 'runway_standard',
    name: 'Standard Jet Runway (2800m)',
    category: 'runways',
    cost: 320000,
    maintenanceCost: 900,
    width: 32,
    height: 4,
    description: 'Main commercial runway for A320, B737 narrow-body aircraft.',
    color: '#1e293b',
    icon: 'PlaneTakeoff',
    requiredLevel: 2,
  },
  {
    id: 'runway_heavy',
    name: 'Heavy CAT-III Runway (3800m)',
    category: 'runways',
    cost: 650000,
    maintenanceCost: 1800,
    width: 40,
    height: 5,
    description: 'All-weather reinforced runway for B787, A350, and heavy freight haulers.',
    color: '#0f172a',
    icon: 'Plane',
    requiredLevel: 4,
  },

  // TAXIWAYS
  {
    id: 'taxiway_straight',
    name: 'Taxiway Segment',
    category: 'taxiways',
    cost: 12000,
    maintenanceCost: 60,
    width: 4,
    height: 2,
    description: 'Smooth asphalt taxiway connector with guidance yellow lines.',
    color: '#475569',
    icon: 'Route',
    requiredLevel: 1,
  },
  {
    id: 'taxiway_junction',
    name: 'High-Speed Exit Taxiway',
    category: 'taxiways',
    cost: 35000,
    maintenanceCost: 120,
    width: 6,
    height: 3,
    description: 'Angled rapid-turnoff taxiway to reduce runway occupancy times.',
    color: '#334155',
    icon: 'GitFork',
    requiredLevel: 2,
  },

  // TERMINALS
  {
    id: 'terminal_regional',
    name: 'Regional Concourse',
    category: 'terminals',
    cost: 85000,
    maintenanceCost: 350,
    width: 14,
    height: 6,
    capacity: 250,
    description: 'Cozy passenger terminal with 4 check-in desks and 1 security lane.',
    color: '#0284c7',
    icon: 'Building2',
    requiredLevel: 1,
  },
  {
    id: 'terminal_standard',
    name: 'Terminal 1 Main Pier',
    category: 'terminals',
    cost: 220000,
    maintenanceCost: 850,
    width: 22,
    height: 7,
    capacity: 800,
    description: 'Spacious glass atrium with modern check-in, TSA security, and boarding lounges.',
    color: '#0369a1',
    icon: 'Building',
    requiredLevel: 2,
  },
  {
    id: 'terminal_international',
    name: 'International Terminal 2',
    category: 'terminals',
    cost: 580000,
    maintenanceCost: 2200,
    width: 28,
    height: 9,
    capacity: 2200,
    description: 'High-throughput world terminal with immigration, customs, and luxury lounges.',
    color: '#1d4ed8',
    icon: 'Landmark',
    requiredLevel: 3,
  },

  // GATES
  {
    id: 'gate_regional',
    name: 'Regional Apron Gate',
    category: 'gates',
    cost: 45000,
    maintenanceCost: 200,
    width: 5,
    height: 5,
    description: 'Walk-up airstairs boarding gate for turboprops and short-haul jets.',
    color: '#0ea5e9',
    icon: 'DoorOpen',
    requiredLevel: 1,
  },
  {
    id: 'gate_standard_jetway',
    name: 'Jetway Gate (A1-A4)',
    category: 'gates',
    cost: 95000,
    maintenanceCost: 400,
    width: 6,
    height: 6,
    description: 'Glass-enclosed telescoping aerobridge gate for rapid passenger embarkation.',
    color: '#2563eb',
    icon: 'Navigation',
    requiredLevel: 2,
  },
  {
    id: 'gate_widebody',
    name: 'Dual-Jetway Widebody Gate',
    category: 'gates',
    cost: 190000,
    maintenanceCost: 800,
    width: 8,
    height: 7,
    description: 'Twin-bridge heavy gate capable of handling B787, A350, and 350+ passengers.',
    color: '#4f46e5',
    icon: 'Maximize2',
    requiredLevel: 3,
  },

  // SERVICES
  {
    id: 'service_fuel',
    name: 'Jet-A1 Fuel Depot',
    category: 'services',
    cost: 65000,
    maintenanceCost: 280,
    width: 6,
    height: 5,
    description: 'Storage tanks and dedicated bowser trucks for rapid refueling operations.',
    color: '#d97706',
    icon: 'Fuel',
    requiredLevel: 1,
  },
  {
    id: 'service_maintenance',
    name: 'Aircraft Maintenance Hangar',
    category: 'services',
    cost: 140000,
    maintenanceCost: 650,
    width: 8,
    height: 6,
    description: 'Full hangar for turnaround inspection, engine diagnostics, and line repairs.',
    color: '#475569',
    icon: 'Wrench',
    requiredLevel: 2,
  },
  {
    id: 'service_baggage',
    name: 'Automated Baggage Sorting Center',
    category: 'services',
    cost: 110000,
    maintenanceCost: 500,
    width: 7,
    height: 5,
    description: 'High-speed baggage conveyor belts and tug trailers ensuring zero lost bags.',
    color: '#ca8a04',
    icon: 'Luggage',
    requiredLevel: 2,
  },
  {
    id: 'service_catering',
    name: 'In-Flight Catering Kitchen',
    category: 'services',
    cost: 75000,
    maintenanceCost: 320,
    width: 5,
    height: 4,
    description: 'Prepares fresh meals and loads catering carts into departing aircraft.',
    color: '#e11d48',
    icon: 'Utensils',
    requiredLevel: 2,
  },
  {
    id: 'service_atc_tower',
    name: 'Air Traffic Control Tower',
    category: 'services',
    cost: 180000,
    maintenanceCost: 750,
    width: 4,
    height: 4,
    description: 'State-of-the-art radar tower providing 24/7 runway sequencing and clearance.',
    color: '#0891b2',
    icon: 'Radio',
    requiredLevel: 1,
  },

  // COMMERCIAL
  {
    id: 'comm_cafe',
    name: 'Aviation Coffee Roasters',
    category: 'commercial',
    cost: 30000,
    maintenanceCost: 100,
    width: 4,
    height: 3,
    description: 'Premium coffee kiosk. Generates ₹4,500 daily profit from waiting passengers.',
    color: '#b45309',
    icon: 'Coffee',
    requiredLevel: 1,
  },
  {
    id: 'comm_dutyfree',
    name: 'Grand Duty-Free Galleria',
    category: 'commercial',
    cost: 120000,
    maintenanceCost: 400,
    width: 7,
    height: 4,
    description: 'Luxury perfumes, watches, and electronics generating ₹24,000 daily revenue.',
    color: '#9333ea',
    icon: 'ShoppingBag',
    requiredLevel: 2,
  },
  {
    id: 'comm_foodcourt',
    name: 'Skyview Food Court',
    category: 'commercial',
    cost: 85000,
    maintenanceCost: 320,
    width: 6,
    height: 4,
    description: 'Diverse multi-cuisine dining hub boosting passenger happiness by +12%.',
    color: '#ea580c',
    icon: 'UtensilsCrossed',
    requiredLevel: 2,
  },

  // TRANSPORT
  {
    id: 'trans_parking',
    name: 'Multi-Level Car Park',
    category: 'transport',
    cost: 50000,
    maintenanceCost: 150,
    width: 8,
    height: 6,
    description: '250 parking bays generating steady daily hourly parking fees.',
    color: '#3b82f6',
    icon: 'Car',
    requiredLevel: 1,
  },
  {
    id: 'trans_bus_metro',
    name: 'Airport Metro Express Station',
    category: 'transport',
    cost: 210000,
    maintenanceCost: 650,
    width: 10,
    height: 4,
    description: 'Direct high-speed rail line to downtown city, boosting passenger influx by +35%.',
    color: '#10b981',
    icon: 'Train',
    requiredLevel: 3,
  },

  // CITY DEVELOPMENT
  {
    id: 'city_hotel',
    name: 'Airport Transit Hotel',
    category: 'city',
    cost: 240000,
    maintenanceCost: 800,
    width: 8,
    height: 6,
    description: '4-star hotel for layovers and flight crews, generating ₹28,000/day profit.',
    color: '#059669',
    icon: 'Hotel',
    requiredLevel: 2,
  },
  {
    id: 'city_cargo',
    name: 'Global Air Cargo Terminal',
    category: 'city',
    cost: 310000,
    maintenanceCost: 1100,
    width: 10,
    height: 6,
    description: 'Dedicated air freight hub handling palletized cargo and express parcels.',
    color: '#64748b',
    icon: 'Package',
    requiredLevel: 2,
  },
];
